# ext_weil.py -- main computation (Sage+GAP): extend the general Weil search beyond D = 16 for selected degree-16 cases.
# usage: sage -python ext_weil.py Dmax [selector]     selector: 'd4' (default) = all primitive cases with d >= 3
# Same unit model as weil_tiers.py (K' <-> M, rho not in M, [G:M] <= Dmax), DFS over multiplicity vectors c with
# sum |c_j| weight_j <= Dmax, incremental balance sums.  Reports, per D level: rank, saturation index of the lattice
# generated by all Weil characters of dimension <= D, and the field indices used.
import sys, os, json, time
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from sage.all import libgap, matrix, ZZ, prod
from cmenum import rho_perm, perm_list
from weil_tiers import units_for


def dfs_chars(units, ntau, g, Dmax):
    """yield (D, chis) for all nonzero balanced c with D <= Dmax."""
    out = {}
    nu = len(units)
    cvec = [0] * nu
    def rec(j, budget, ssum, chis, D):
        if j == nu:
            if D > 0 and not any(ssum):
                key = D
                for w in chis:
                    if any(w):
                        out.setdefault(key, set()).add(tuple(w))
            return
        u = units[j]
        w = u['weight']
        m = budget // w
        for c in range(-m, m + 1):
            if c == 0:
                rec(j + 1, budget, ssum, chis, D)
                continue
            ns = [a + c * b for a, b in zip(ssum, u['s'])]
            nch = [[a + c * b for a, b in zip(ch, be)] for ch, be in zip(chis, u['beta'])]
            rec(j + 1, budget - abs(c) * w, ns, nch, D + abs(c) * w)
    rec(0, Dmax, [0] * ntau, [[0] * g for _ in range(ntau)], 0)
    return out


def ext_case(G, g, Phi, d, LU, Dmax):
    n = 2 * g
    rho = rho_perm(g)
    ggens = list(libgap.GeneratorsOfGroup(G))
    gl = [perm_list(x, n) for x in ggens]
    orbs = sorted([sorted(int(x) - 1 for x in o) for o in libgap.Orbits(G, list(range(1, n + 1)))], key=min)
    Ps = set(Phi)
    byD = {}
    subs = libgap.LowIndexSubgroups(G, Dmax)
    t0 = time.time()
    for Mid, M in enumerate(subs):
        if bool(libgap.IsSubset(M, [rho])):
            continue
        idx, taus, units = units_for(G, gl, ggens, orbs, M, g, rho)
        for u in units:
            u['s'] = [2 * len(Ps & set(F)) - len(F) for F in u['F']]
        units = [u for u in units if u['weight'] <= Dmax and any(any(b) for b in u['beta'])]
        if not units:
            continue
        res = dfs_chars(units, len(taus), g, Dmax)
        for D, chs in res.items():
            assert D % (idx // 2) == 0 and (D // (idx // 2)) % 2 == 0
            for w in chs:
                byD.setdefault(D, {}).setdefault(idx, set()).add(w)
    levels = []
    acc = []
    used = set()
    for D in sorted(byD):
        for idx, ws in byD[D].items():
            acc += [list(w) for w in ws]
            used.add(idx)
        Mx = matrix(ZZ, acc)
        assert matrix(ZZ, LU + acc).rank() == d
        r = Mx.rank()
        sat = None
        if r == d:
            ed = [int(x) for x in Mx.elementary_divisors() if x != 0]
            sat = int(prod(ed))
        levels.append(dict(D=D, rank=r, satindex=sat, indices=sorted(used),
                           new_indices_at_D=sorted(byD[D].keys())))
    return levels, time.time() - t0


if __name__ == '__main__' and len(sys.argv) > 2 and sys.argv[2].startswith('g7:'):
    # Stage C mode: ext_weil.py Dmax g7:gid1,gid2,...  (reduced strict failures with no lattice up to D=16)
    Dmax = int(sys.argv[1])
    gids = set(int(x) for x in sys.argv[2][3:].split(','))
    D = json.load(open(HERE + '/enum_g7.json'))
    groups = {G['gid']: G for G in D['groups']}
    out = []
    seen = set()
    for c in D['cases']:
        if c['gid'] not in gids or 'general' not in c or (c['gid'], c['Nclass']) in seen:
            continue
        seen.add((c['gid'], c['Nclass']))
        Gr = groups[c['gid']]
        G = libgap.Group([libgap.PermList([x + 1 for x in p]) for p in Gr['gens']])
        levels, dt = ext_case(G, 7, c['Phi'], c['d'], c['LU'], Dmax)
        out.append(dict(gid=c['gid'], Phi=c['Phi'], d=c['d'], LU=c['LU'], levels=levels, time=dt))
        print('g7 gid', c['gid'], Gr['orbit_TI'], c['Phi'], 'd=%d' % c['d'], ['D%d:r%d/s%s/%s' % (l['D'], l['rank'], l['satindex'], l['indices']) for l in levels], '%.1fs' % dt, flush=True)
    json.dump(out, open(HERE + '/ext_weil_g7_D%d.json' % Dmax, 'w'), default=int)
    sys.exit(0)

if __name__ == '__main__':
    Dmax = int(sys.argv[1])
    D = json.load(open(HERE + '/trans_g8.json'))
    g = 8
    out = []
    t0 = time.time()
    only = set(sys.argv[2].split(',')) if len(sys.argv) > 2 else None
    for Gr in D['groups']:
        if only is not None and Gr['TI'] not in only:
            continue
        seen = set()
        for c in Gr['cases']:
            if not (c['primitive'] and c['d'] >= 3) or c['Nclass'] in seen:
                continue
            seen.add(c['Nclass'])
            G = libgap.Group([libgap.PermList([x + 1 for x in p]) for p in Gr['gens']])
            levels, dt = ext_case(G, g, c['Phi'], c['d'], c['LU'], Dmax)
            rec = dict(TI=Gr['TI'], j=Gr['j'], order=Gr['order'], Phi=c['Phi'], d=c['d'], LU=c['LU'], levels=levels, time=dt)
            out.append(rec)
            print(Gr['TI'], Gr['j'], Gr['order'], c['Phi'], 'd=%d' % c['d'], ['D%d:r%d/s%s/%s' % (l['D'], l['rank'], l['satindex'], l['indices']) for l in levels],
                  '%.1fs' % dt, flush=True)
    json.dump(out, open(HERE + '/ext_weil_D%d%s.json' % (Dmax, '_sel' if only else ''), 'w'), default=int)
    print("time %.1fs" % (time.time() - t0))
